// RSS лента: https://proverki.gov.ru/blob/opendata/list.xml
// https://proverki.gov.ru/portal/public-open-data
// jsonschema_description
// https://proverki.gov.ru/public/api/opendata/2021/1?isFederalLaw248=false
// https://proverki.gov.ru/public/api/opendata/plans/2021?isFederalLaw248=false

package models

type InspectionFGIS struct {
	ERPID               string                `xml:"ERPID,attr" jsonschema_description:"Учетный номер КНМ в соответствии с постановлением Правительства РФ от 28 апреля 2015 г. N 415 \"О Правилах формирования и ведения единого реестра проверок\""`                                                               // Учетный номер КНМ в соответствии с постановлением Правительства РФ от 28 апреля 2015 г. N 415 "О Правилах формирования и ведения единого реестра проверок"
	ITYPE_NAME          string                `xml:"ITYPE_NAME,attr" jsonschema_description:"Тип КНМ"`                                                                                                                                                                                                               // Тип КНМ
	FZ_NAME             string                `xml:"FZ_NAME,attr" jsonschema_description:"Федеральный закон, в соответствии с которым проводится КНМ"`                                                                                                                                                               // Федеральный закон, в соответствии с которым проводится КНМ
	PROSEC_NAME         string                `xml:"PROSEC_NAME,attr" jsonschema_description:"Наименование прокуратуры"`                                                                                                                                                                                             // Наименование прокуратуры
	START_DATE          string                `xml:"START_DATE,attr" jsonschema_description:"Дата начала проведения мероприятия"`                                                                                                                                                                                    // Дата начала проведения мероприятия
	STATUS              string                `xml:"STATUS,attr" jsonschema_description:"Статус КНМ"`                                                                                                                                                                                                                // Статус КНМ
	ERPID_DATE_CREATE   *string               `xml:"ERPID_DATE_CREATE,attr" json:"ERPID_DATE_CREATE,omitempty" jsonschema_description:"Дата получения учетного номера КНМ в соответствии с постановлением Правительства РФ от 28 апреля 2015 г. N 415 «О Правилах формирования и ведения единого реестра проверок»"` // Дата получения учетного номера КНМ в соответствии с постановлением Правительства РФ от 28 апреля 2015 г. N 415 «О Правилах формирования и ведения единого реестра проверок»
	OKATO               OKATO_fgis            `xml:"OKATO" jsonschema_description:"Вид территориальной юрисдикции"`                                                                                                                                                                                                  // Комплексный тип - Вид территориальной юрисдикции
	I_SUBJECT           I_SUBJECT             `xml:"I_SUBJECT" jsonschema_description:"Cубъект КНМ"`                                                                                                                                                                                                                 // Cубъект КНМ
	I_CLASSIFICATION    I_CLASSIFICATION      `xml:"I_CLASSIFICATION" jsonschema_description:"Общий состав атрибутов для классификации КНМ"`                                                                                                                                                                         // Общий состав атрибутов для классификации КНМ
	I_AUTHORITY         I_AUTHORITY           `xml:"I_AUTHORITY" jsonschema_description:"Орган контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ) проводящий КНМ"`                                                                                                              // Орган контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ) проводящий КНМ
	I_APPROVE           I_APPROVE             `xml:"I_APPROVE" jsonschema_description:"Сведения о согласовании проведения КНМ с органом прокуратуры"`                                                                                                                                                                // Сведения о согласовании проведения КНМ с органом прокуратуры
	Requirements        *Requirements_fgis    `xml:"requirements" json:"requirements,omitempty" jsonschema_description:"Обязательные требования КНМ"`                                                                                                                                                                // Обязательные требования КНМ
	I_OBJECT            []I_OBJECT            `xml:"I_OBJECT" jsonschema_description:"Объект КНМ, комплекс атрибутов, описывающих объект проверки"`                                                                                                                                                                  // Объект КНМ, комплекс атрибутов, описывающих объект проверки
	I_INSPECTOR         []I_INSPECTOR         `xml:"I_INSPECTOR" json:"I_INSPECTOR,omitempty" jsonschema_description:"Уполномоченное должностное лицо на проведение КНМ, или эксперт, представитель экспертной организации, привлекаемый к проведению КНМ"`                                                          // Уполномоченное должностное лицо на проведение КНМ, или эксперт, представитель экспертной организации, привлекаемый к проведению КНМ
	I_CLASSIFICATION_LB []I_CLASSIFICATION_LB `xml:"I_CLASSIFICATION_LB" json:"I_CLASSIFICATION_LB,omitempty" jsonschema_description:"Правовое основание КНМ"`                                                                                                                                                       // Правовое основание КНМ
	// SmevInteractions    SmevInteractions      `xml:"smevInteractions" jsonschema_description:"Взаимодействия по КНМ со СМЭВ"`                                                                                                                                                     // Взаимодействия по КНМ со СМЭВ
}

func (ins InspectionFGIS) INN() string {
	return ins.I_SUBJECT.INN
}

func (ins InspectionFGIS) OGRN() string {
	return ins.I_SUBJECT.OGRN
}

type RequiredDocumentERP struct {
	TemplateRequirementName      string  `xml:"templateRequirementName,attr" jsonschema_description:"Наименование НПА"`          // Наименование НПА
	TemplateRequirementProps     string  `xml:"templateRequirementProps,attr" jsonschema_description:"Реквизит НПА"`             // Реквизит НПА
	TemplateRequirementNumber    string  `xml:"templateRequirementNumber,attr" jsonschema_description:"Номер НПА"`               // Номер НПА
	TemplateRequirementDate      *string `xml:"templateRequirementDate,attr" json:"omitempty" jsonschema_description:"Дата НПА"` // Дата НПА
	TemplateRequirementParagraph string  `xml:"templateRequirementParagraph,attr" jsonschema_description:"Пункт НПА"`            // Пункт НПА
	TemplateRequirementPart      string  `xml:"templateRequirementPart,attr" jsonschema_description:"Часть НПА"`                 // Часть НПА
	TemplateRequirementArticle   string  `xml:"templateRequirementArticle,attr" jsonschema_description:"Статья НПА"`             // Статья НПА
}

type OKATO_fgis struct {
	FEDERAL_DISTRICT string `xml:"FEDERAL_DISTRICT,attr" jsonschema_description:"Код федерального округа. Общероссийский классификатор экономических регионов (ОКЭР)."`                 // Код федерального округа. Общероссийский классификатор экономических регионов (ОКЭР).
	OKATO_RAZDEL     uint8  `xml:"OKATO_RAZDEL,attr" jsonschema_description:"Код раздела (ОКАТО). Указание на уровень классификации объекта административно-территориального деления."` // Код раздела (ОКАТО). Указание на уровень классификации объекта административно-территориального деления.
	OKATO_TER        string `xml:"OKATO_TER,attr" jsonschema_description:"Код региона (ОКАТО)"`                                                                                         // Код региона (ОКАТО)
	OKATO_KOD1       string `xml:"OKATO_KOD1,attr" jsonschema_description:"Код района (ОКАТО)"`                                                                                         // Код района (ОКАТО)
	OKATO_KOD2       string `xml:"OKATO_KOD2,attr" jsonschema_description:"Код рабочего поселка/сельсовета (ОКАТО)"`                                                                    // Код рабочего поселка/сельсовета (ОКАТО)
	OKATO_KOD3       string `xml:"OKATO_KOD3,attr" jsonschema_description:"Код сельского населенного пункта (ОКАТО)"`                                                                   // Код сельского населенного пункта (ОКАТО)
	OKATO_NAME       string `xml:"OKATO_NAME,attr" jsonschema_description:"Назвыание (ОКАТО)"`                                                                                          // Назвыание (ОКАТО)
}

type I_SUBJECT struct {
	IS_RESIDENT            bool    `xml:"IS_RESIDENT,attr" jsonschema_description:"Субъект проверки - Резидент РФ"`                                                                                                                                                                                                                           // Субъект проверки - Резидент РФ
	ISUBJECT_TYPE_NAME     string  `xml:"ISUBJECT_TYPE_NAME,attr" jsonschema_description:"Тип субъекта КНМ"`                                                                                                                                                                                                                                  // Тип субъекта КНМ
	ORG_NAME               string  `xml:"ORG_NAME,attr" jsonschema_description:"Наименование юридического лица (ЮЛ) или фамилия, имя, отчество (последнее – при наличии) индивидуального предпринимателя, в отношении которого проводится КНМ"`                                                                                               // Наименование юридического лица (ЮЛ) или фамилия, имя, отчество (последнее – при наличии) индивидуального предпринимателя, в отношении которого проводится КНМ
	INN                    string  `xml:"INN,attr" jsonschema_description:"ИНН проверяемого лица"`                                                                                                                                                                                                                                            // ИНН проверяемого лица
	OGRN                   string  `xml:"OGRN,attr" jsonschema_description:"ОГРН проверяемого лица"`                                                                                                                                                                                                                                          // ОГРН проверяемого лица
	DATE_REG               *string `xml:"DATE_REG,attr" json:"DATE_REG,omitempty" jsonschema_description:"Дата присвоения ОГРН (дата регистрации) юридического лица (ЮЛ) или индивидуального предпринимателя (ИП)"`                                                                                                                           // Дата присвоения ОГРН (дата регистрации) юридического лица (ЮЛ) или индивидуального предпринимателя (ИП)
	DATE_ESTABLISH         *string `xml:"DATE_ESTABLISH,attr" json:"DATE_ESTABLISH,omitempty" jsonschema_description:"Дата основания юридического лица (ЮЛ) или индивидуального предпринимателя (ИП)"`                                                                                                                                        // Дата основания юридического лица (ЮЛ) или индивидуального предпринимателя (ИП)
	DATE_LAST_INSPECTION   *string `xml:"DATE_LAST_INSPECTION,attr" json:"DATE_LAST_INSPECTION,omitempty" jsonschema_description:"Дата проведения последнего КНМ в отношении проверяемого лица"`                                                                                                                                              // Дата проведения последнего КНМ в отношении проверяемого лица
	LICENCE_REASON_I       string  `xml:"LICENCE_REASON_I,attr" jsonschema_description:"Информация о постановлении о назначении административного назначения или решении о приостановлении и (или) аннулировании лицензии. Реквизиты постановления или решения."`                                                                             // Информация о постановлении о назначении административного назначения или решении о приостановлении и (или) аннулировании лицензии. Реквизиты постановления или решения.
	LICENCE_REASON_DATE_I  *string `xml:"LICENCE_REASON_DATE_I,attr" json:"LICENCE_REASON_DATE_I,omitempty" jsonschema_description:"Информация о постановлении о назначении административного назначения или решении о приостановлении и (или) аннулировании лицензии: Дата вступления в законную силу постановления или решения."`           // Информация о постановлении о назначении административного назначения или решении о приостановлении и (или) аннулировании лицензии: Дата вступления в законную силу постановления или решения.
	LICENCE_REASON_DATE_II *string `xml:"LICENCE_REASON_DATE_II,attr" json:"LICENCE_REASON_DATE_II,omitempty" jsonschema_description:"Информация о постановлении о назначении административного назначения или решении о приостановлении и (или) аннулировании лицензии: Дата окончания проведения КНМ, по результатам которой они приняты."` // Информация о постановлении о назначении административного назначения или решении о приостановлении и (или) аннулировании лицензии: Дата окончания проведения КНМ, по результатам которой они приняты.
}

type I_CLASSIFICATION struct {
	ICARRYOUT_TYPE_NAME  string  `xml:"ICARRYOUT_TYPE_NAME,attr" jsonschema_description:"Форма проведения КНМ"`                                                                                                                                                   // Форма проведения КНМ
	ISUPERVISION_NAME    string  `xml:"ISUPERVISION_NAME,attr" jsonschema_description:"Вид государственного контроля (надзора)"`                                                                                                                                  // Вид государственного контроля (надзора)
	INOTICE_TYPE_NAME    string  `xml:"INOTICE_TYPE_NAME,attr" jsonschema_description:"Способ уведомления проверяемого лица о проведении КНМ"`                                                                                                                    // Способ уведомления проверяемого лица о проведении КНМ
	ISUPERVISION_ID      uint64  `xml:"ISUPERVISION_ID,attr" jsonschema_description:"Вид государственного контроля (надзора) - Идентификатор"`                                                                                                                    // Вид государственного контроля (надзора) - Идентификатор
	IRISK_NAME           string  `xml:"IRISK_NAME,attr" jsonschema_description:"Классификация КНМ по категориям риска и классу опасности (категории опасности) деятельности проверяемого лица (юридического лица (ЮЛ) или индивидуального предпринимателя (ИП))"` // Классификация КНМ по категориям риска и классу опасности (категории опасности) деятельности проверяемого лица (юридического лица (ЮЛ) или индивидуального предпринимателя (ИП))
	INOTICE_DATE         *string `xml:"INOTICE_DATE,attr" json:"INOTICE_DATE,omitempty" jsonschema_description:"Способ уведомления проверяемого лица о проведении КНМ"`                                                                                           // Способ уведомления проверяемого лица о проведении КНМ
	SPENDING_TYPE_NAME   string  `xml:"SPENDING_TYPE_NAME,attr" jsonschema_description:"Способ проведения контрольной закупки"`                                                                                                                                   // Способ проведения контрольной закупки
	SPENDING_DESCRIPTION string  `xml:"SPENDING_DESCRIPTION,attr" jsonschema_description:"Описание закупки"`                                                                                                                                                      // Описание закупки
}

type I_CLASSIFICATION_LB struct {
	ATR_DATE              *string `xml:"ATR_DATE,attr" json:"ATR_DATE,omitempty" jsonschema_description:"Дата нормативно-правового акта"` // Дата нормативно-правового акта
	ATR_NUMBER            string  `xml:"ATR_NUMBER,attr" jsonschema_description:"Номер нормативно-правового акта"`                        // Номер нормативно-правового акта
	LB_DOCUMENT_NAME      string  `xml:"LB_DOCUMENT_NAME,attr" jsonschema_description:"Положение нормативно-правового акта"`              // Положение нормативно-правового акта
	ATR_I                 string  `xml:"ATR_I,attr" jsonschema_description:"Положение нормативно-правового акта.Раздел"`                  // Положение нормативно-правового акта.Раздел
	ATR_II                string  `xml:"ATR_II,attr" jsonschema_description:"Положение нормативно-правового акта.Глава"`                  // Положение нормативно-правового акта.Глава
	ATR_III               string  `xml:"ATR_III,attr" jsonschema_description:"Положение нормативно-правового акта.Статья"`                // Положение нормативно-правового акта.Статья
	ATR_IV                string  `xml:"ATR_IV,attr" jsonschema_description:"Положение нормативно-правового акта.Пункт"`                  // Положение нормативно-правового акта.Пункт
	ATR_V                 string  `xml:"ATR_V,attr" jsonschema_description:"Положение нормативно-правового акта.Часть"`                   // Положение нормативно-правового акта.Часть
	LB_TYPE_POINTING_NAME string  `xml:"LB_TYPE_POINTING_NAME,attr" jsonschema_description:"Тип положения нормативно-правового акта"`     // Тип положения нормативно-правового акта
}

type Requirements_fgis struct {
	RequirementName string                `xml:"requirementName,attr" jsonschema_description:"Наименование требования"`  // Наименование требования
	Documents       []RequiredDocumentERP `xml:"documents" jsonschema_description:"Общий состав атрибутов паспорта КНМ"` // Общий состав атрибутов паспорта КНМ
}

type SmevInteractions struct {
	Vs_ver        string `xml:"Vs_ver,attr" jsonschema_description:"Версия ВС"`                                        // Версия ВС
	Exchange_Date string `xml:"Exchange_Date,attr" jsonschema_description:"Дата и время взаимодействия в формате UTC"` // Дата и время взаимодействия в формате UTC
}

type I_INSPECTOR struct {
	FULL_NAME           string `xml:"FULL_NAME,attr" jsonschema_description:"ФИО должностного лица, уполномоченного на проведение КНМ"`           // ФИО должностного лица, уполномоченного на проведение КНМ
	POSITION            string `xml:"POSITION,attr" jsonschema_description:"Должность должностного лица, уполномоченного на проведение КНМ"`      // Должность должностного лица, уполномоченного на проведение КНМ
	INSPECTOR_TYPE_NAME string `xml:"INSPECTOR_TYPE_NAME,attr" jsonschema_description:"Тип должностного лица, уполномоченного на проведение КНМ"` // Тип должностного лица, уполномоченного на проведение КНМ
}

type I_AUTHORITY struct {
	FRGU_ORG_ID_BK        string               `xml:"FRGU_ORG_ID_BK,attr" jsonschema_description:"Идентификатор органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)"`                                                                          // Идентификатор органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)
	FRGU_ORG_NAME         string               `xml:"FRGU_ORG_NAME,attr" jsonschema_description:"Наименование органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ"`                                                                             // Наименование органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ
	FRGU_ORG_OGRN         string               `xml:"FRGU_ORG_OGRN,attr" jsonschema_description:"ОГРН органа государственного контроля (надзора)"`                                                                                                                                        // ОГРН органа государственного контроля (надзора)
	FRGU_ORG_PARENT_ID_BK string               `xml:"FRGU_ORG_PARENT_ID_BK,attr" jsonschema_description:"Идентификатор органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ) вышестоящей организации"`                                           // Идентификатор органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ) вышестоящей организации
	FRGU_ORG_ADMIN_LEVEL  string               `xml:"FRGU_ORG_ADMIN_LEVEL,attr" jsonschema_description:"Административный уровень органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)"`                                                         // Административный уровень органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)
	KO_JOINTLY            string               `xml:"KO_JOINTLY,attr" jsonschema_description:"Наименование органа контроля (надзора), совместно с которым проводится КНМ"`                                                                                                                // Наименование органа контроля (надзора), совместно с которым проводится КНМ
	I_AUTHORITY_SERV      *I_AUTHORITY_SERV    `xml:"I_AUTHORITY_SERV" json:"I_AUTHORITY_SERV,omitempty" jsonschema_description:"Контрольно-надзорная функция из Федерального реестра государственных и муниципальных услуг (ФРГУ), привязанная к КНМ"`                                   // Контрольно-надзорная функция из Федерального реестра государственных и муниципальных услуг (ФРГУ), привязанная к КНМ
	I_AUTHORITY_JOINTLY   *I_AUTHORITY_JOINTLY `xml:"I_AUTHORITY_JOINTLY" json:"I_AUTHORITY_JOINTLY,omitempty" jsonschema_description:"Наименование органа контроля (надзора), органа муниципального контроля, с которым КНМ проводится совместно (в соответствии со справочником ФРГУ)"` // Наименование органа контроля (надзора), органа муниципального контроля, с которым КНМ проводится совместно (в соответствии со справочником ФРГУ)
}

type I_AUTHORITY_SERV struct {
	FRGU_SERV_ID_BK string `xml:"FRGU_SERV_ID_BK,attr" jsonschema_description:"Идентификатор контрольно-надзорной функции из Федерального реестра государственных и муниципальных услуг (ФРГУ)"` // Идентификатор контрольно-надзорной функции из Федерального реестра государственных и муниципальных услуг (ФРГУ)
	FRGU_SERV_NAME  string `xml:"FRGU_SERV_NAME,attr" jsonschema_description:"Наименование контрольно-надзорной функции из Федерального реестра государственных и муниципальных услуг (ФРГУ)"`   // Наименование контрольно-надзорной функции из Федерального реестра государственных и муниципальных услуг (ФРГУ)
}

type I_AUTHORITY_JOINTLY struct {
	JOINTLY_FRGU_ORG_ID_BK string `xml:"JOINTLY_FRGU_ORG_ID_BK,attr" jsonschema_description:"Идентификатор органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)"` // Идентификатор органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)
	JOINTLY_FRGU_ORG_NAME  string `xml:"JOINTLY_FRGU_ORG_NAME,attr" jsonschema_description:"Наименование органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)"`   // Наименование органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)
}

type I_APPROVE struct {
	IS_START_DATE_AS_MONTH bool               `xml:"IS_START_DATE_AS_MONTH,attr" jsonschema_description:"Метка об указании только месяца проведения (КНМ) для плановых КНМ"`                                         // Метка об указании только месяца проведения (КНМ) для плановых КНМ
	DURATION_DAY           uint64             `xml:"DURATION_DAY,attr" jsonschema_description:"Срок проведения КНМ (в рабочих днях)"`                                                                                // Срок проведения КНМ (в рабочих днях)
	DURATION_HOURS         uint64             `xml:"DURATION_HOURS,attr" jsonschema_description:"Срок проведения КНМ (в рабочих часах)"`                                                                             // Срок проведения КНМ (в рабочих часах)
	EXT_DURATION_DAY       uint64             `xml:"EXT_DURATION_DAY,attr" jsonschema_description:"Расширенный (продление) срок проведения КНМ (в днях)"`                                                            // Расширенный (продление) срок проведения КНМ (в днях)
	EXT_DURATION_HOURS     uint64             `xml:"EXT_DURATION_HOURS,attr" jsonschema_description:"Расширенный (продление) срок проведения КНМ (в часах)"`                                                         // Расширенный (продление) срок проведения КНМ (в часах)
	DECISION_PLACE         string             `xml:"DECISION_PLACE,attr" jsonschema_description:"Место вынесения решения о согласовании проведения КНМ органом прокуратуры"`                                         // Место вынесения решения о согласовании проведения КНМ органом прокуратуры
	DECISION_SIGNER_TITLE  string             `xml:"DECISION_SIGNER_TITLE,attr" jsonschema_description:"Должность подписанта о согласовании проведения КНМ органа прокуратуры"`                                      // Должность подписанта о согласовании проведения КНМ органа прокуратуры
	DECISION_SIGNER_NAME   string             `xml:"DECISION_SIGNER_NAME,attr" jsonschema_description:"ФИО подписанта о согласовании проведения КНМ органа прокуратуры"`                                             // ФИО подписанта о согласовании проведения КНМ органа прокуратуры
	IS_APPROVED            bool               `xml:"IS_APPROVED,attr" jsonschema_description:"Отметка о включении плановой проверки (КНМ) в ежегодный сводный план проведения плановых проверок"`                    // Отметка о включении плановой проверки (КНМ) в ежегодный сводный план проведения плановых проверок
	INSP_TARGET            string             `xml:"INSP_TARGET,attr" jsonschema_description:"Цели, задачи, предмет КНМ"`                                                                                            // Цели, задачи, предмет КНМ
	I_CARRYOUT_EVENTS      *I_CARRYOUT_EVENTS `xml:"I_CARRYOUT_EVENTS" json:"I_CARRYOUT_EVENTS,omitempty" jsonschema_description:"Мероприятие по контролю, необходимое для достижения целей и задач проведения КНМ"` // Мероприятие по контролю, необходимое для достижения целей и задач проведения КНМ
	I_REASON               *I_REASON          `xml:"I_REASON" json:"I_REASON,omitempty" jsonschema_description:"Комплексный тип - Правовое основание проведения планового КНМ"`                                      // Комплексный тип - Правовое основание проведения планового КНМ
	I_REASON_DENY          *I_REASON_DENY     `xml:"I_REASON_DENY" json:"I_REASON_DENY,omitempty" jsonschema_description:"Причина отказа в проведении КНМ"`                                                          // Причина отказа в проведении КНМ
	I_APPROVE_DOCS         *I_APPROVE_DOCS    `xml:"I_APPROVE_DOCS" json:"I_APPROVE_DOCS,omitempty" jsonschema_description:"Комплексный тип - Документ о согласовании (продлении) КНМ"`                              // Комплексный тип - Документ о согласовании (продлении) КНМ
}

type I_CARRYOUT_EVENTS struct {
	EVENTS_TEXT string  `xml:"EVENTS_TEXT,attr" jsonschema_description:"Наименование мероприятия по контролю, необходимого для достижения целей и задач проведения КНМ"` // Наименование мероприятия по контролю, необходимого для достижения целей и задач проведения КНМ
	START_DATE  *string `xml:"START_DATE,attr" json:"START_DATE,omitempty" jsonschema_description:"Дата начала проведения мероприятия"`                                  // Дата начала проведения мероприятия
	END_DATE    *string `xml:"END_DATE,attr" json:"END_DATE,omitempty" jsonschema_description:"Дата окончания проведения мероприятия"`                                   // Дата окончания проведения мероприятия
}

type I_REASON struct {
	IREASON_NAME        string  `xml:"IREASON_NAME,attr" jsonschema_description:"Наименование основания проведения КНМ"`                                                                                 // Наименование основания проведения КНМ
	REASON_TEXT         string  `xml:"REASON_TEXT,attr" jsonschema_description:"Основание проведения КНМ"`                                                                                               // Основание проведения КНМ
	REASON_DATE         *string `xml:"REASON_DATE,attr" json:"REASON_DATE,omitempty" jsonschema_description:"Дата, характеризующая один из вариантов основания проведения КНМ как основание проведения"` // Дата, характеризующая один из вариантов основания проведения КНМ как основание проведения
	IS_APPROVE_REQUIRED bool    `xml:"IS_APPROVE_REQUIRED,attr" jsonschema_description:"Сведения о необходимости согласования КНМ"`                                                                      // Сведения о необходимости согласования КНМ
}

type I_REASON_DENY struct {
	IREASON_DENY_NAME string  `xml:"IREASON_DENY_NAME,attr" jsonschema_description:"Наименование оснований в отказе проведения КНМ"`                                                                                         // Наименование оснований в отказе проведения КНМ
	REASON_DENY_TEXT  string  `xml:"REASON_DENY_TEXT,attr" jsonschema_description:"Основание отказа проведения КНМ"`                                                                                                         // Основание отказа проведения КНМ
	REASON_DENY_DATE  *string `xml:"REASON_DENY_DATE,attr" json:"REASON_DENY_DATE,omitempty" jsonschema_description:"Дата, характеризующая один из вариантов отказа в проведении КНМ (если требуется) как основание отказа"` // Дата, характеризующая один из вариантов отказа в проведении КНМ (если требуется) как основание отказа
}

type I_APPROVE_DOCS struct {
	IAPPROVE_DOC_NAME string  `xml:"IAPPROVE_DOC_NAME,attr" jsonschema_description:"Документ о согласовании проведения КНМ"`                                                                                                            // Документ о согласовании проведения КНМ
	DOC_ATR           string  `xml:"DOC_ATR,attr" jsonschema_description:"Номер распоряжения или приказа руководителя (заместителя руководителя) органа контроля (надзора) о проведении КНМ"`                                           // Номер распоряжения или приказа руководителя (заместителя руководителя) органа контроля (надзора) о проведении КНМ
	DOC_DATE          *string `xml:"DOC_DATE,attr" json:"DOC_DATE,omitempty" jsonschema_description:"Дата распоряжения или приказа руководителя (заместителя руководителя) органа контроля (надзора) о продлении срока проведения КНМ"` // Дата распоряжения или приказа руководителя (заместителя руководителя) органа контроля (надзора) о продлении срока проведения КНМ
}

type I_OBJECT struct {
	ADDRESS           string           `xml:"ADDRESS,attr" jsonschema_description:"Адрес объекта проведения КНМ"`                                            // Адрес объекта проведения КНМ
	ADDRESS_TYPE_NAME string           `xml:"ADDRESS_TYPE_NAME,attr" jsonschema_description:"Тип адреса места составления акта о проведении КНМ"`            // Тип адреса места составления акта о проведении КНМ
	IOBJECT_TYPE_NAME string           `xml:"IOBJECT_TYPE_NAME,attr" jsonschema_description:"Тип объекта проведения КНМ"`                                    // Тип объекта проведения КНМ
	IRISK_NAME        string           `xml:"IRISK_NAME,attr" jsonschema_description:"Категория риска"`                                                      // Категория риска
	I_RESULT          *I_RESULT        `xml:"I_RESULT" json:"I_RESULT,omitempty" jsonschema_description:"Результат проведения КНМ"`                          // Результат проведения КНМ
	I_CHLIST_HEADER   *I_CHLIST_HEADER `xml:"I_CHLIST_HEADER" json:"I_CHLIST_HEADER,omitempty" jsonschema_description:"Проверочный лист"`                    // Проверочный лист
	I_SUPERVISION     *I_SUPERVISION   `xml:"I_SUPERVISION" json:"I_SUPERVISION,omitempty" jsonschema_description:"Вид государственного контроля (надзора)"` // Вид государственного контроля (надзора)
}

type I_RESULT struct {
	ACT_DATE_CREATE          string                    `xml:"ACT_DATE_CREATE,attr" jsonschema_description:"Дата и время составления акта о проведении КНМ"`                                                                                                                                                                                                                                                                                      // Дата и время составления акта о проведении КНМ
	ACT_ADDRESS              string                    `xml:"ACT_ADDRESS,attr" jsonschema_description:"Место составления акта о проведении КНМ"`                                                                                                                                                                                                                                                                                                 // Место составления акта о проведении КНМ
	ACT_ADDRESS_TYPE_NAME    string                    `xml:"ACT_ADDRESS_TYPE_NAME,attr" jsonschema_description:"Тип адреса места составления акта о проведении КНМ"`                                                                                                                                                                                                                                                                            // Тип адреса места составления акта о проведении КНМ
	START_DATE               *string                   `xml:"START_DATE,attr" json:"START_DATE,omitempty" jsonschema_description:"Дата начала проведения КНМ (фактическая)"`                                                                                                                                                                                                                                                                     // Дата начала проведения КНМ (фактическая)
	DURATION_DAYS            uint64                    `xml:"DURATION_DAYS,attr" jsonschema_description:"Длительность КНМ (в днях)"`                                                                                                                                                                                                                                                                                                             // Длительность КНМ (в днях)
	DURATION_HOURS           uint64                    `xml:"DURATION_HOURS,attr" jsonschema_description:"Длительность КНМ (в часах)"`                                                                                                                                                                                                                                                                                                           // Длительность КНМ (в часах)
	REPRESENTATIVE_FULL_NAME string                    `xml:"REPRESENTATIVE_FULL_NAME,attr" jsonschema_description:"Фамилия, имя, отчество (последнее – при наличии) руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ"`                                                              // Фамилия, имя, отчество (последнее – при наличии) руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ
	REPRESENTATIVE_POSITION  string                    `xml:"REPRESENTATIVE_POSITION,attr" jsonschema_description:"Должность руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ"`                                                                                                      // Должность руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ
	REPRESENTATIVE_TYPE_NAME string                    `xml:"REPRESENTATIVE_TYPE_NAME,attr" jsonschema_description:"Тип представителя проверяемого лица"`                                                                                                                                                                                                                                                                                        // Тип представителя проверяемого лица
	ACT_WAS_NOT_READ_NOTE    string                    `xml:"ACT_WAS_NOT_READ_NOTE,attr" jsonschema_description:"Сведения об ознакомлении или отказе от ознакомления с актом КНМ руководителя, иного должностного лица или уполномоченного представителя юридического лица, индивидуального предпринимателя, его уполномоченного представителя, присутствовавших при проведении КНМ, о наличии их подписей или об отказе от совершения подписи"` // Сведения об ознакомлении или отказе от ознакомления с актом КНМ руководителя, иного должностного лица или уполномоченного представителя юридического лица, индивидуального предпринимателя, его уполномоченного представителя, присутствовавших при проведении КНМ, о наличии их подписей или об отказе от совершения подписи
	ACT_WAS_NOT_READ         bool                      `xml:"ACT_WAS_NOT_READ,attr" jsonschema_description:"Отметка об ознакомлении или отказе от ознакомления с актом КНМ руководителя, иного должностного лица или уполномоченного представителя юридического лица, индивидуального предпринимателя, его уполномоченного представителя, присутствовавших при проведении КНМ, о наличии их подписей или об отказе от совершения подписи"`       // Отметка об ознакомлении или отказе от ознакомления с актом КНМ руководителя, иного должностного лица или уполномоченного представителя юридического лица, индивидуального предпринимателя, его уполномоченного представителя, присутствовавших при проведении КНМ, о наличии их подписей или об отказе от совершения подписи
	WRONG_DATA_REASON_SEC_I  string                    `xml:"WRONG_DATA_REASON_SEC_I,attr" jsonschema_description:"Сведения о несоответствии информации, содержащейся в уведомлении о начале осуществления отдельных видов предпринимательской деятельности, обязательным требованиям (с указанием положений нормативных правовых актов)"`                                                                                                       // Сведения о несоответствии информации, содержащейся в уведомлении о начале осуществления отдельных видов предпринимательской деятельности, обязательным требованиям (с указанием положений нормативных правовых актов)
	ABSENT_VIOLATION_NOTE    string                    `xml:"ABSENT_VIOLATION_NOTE,attr" jsonschema_description:"Указание на отсутствие выявленных нарушений обязательных требований или требований, установленных муниципальными правовыми актами (в случае если нарушений обязательных требований или требований, установленных муниципальными правовыми актами, не выявлено)"`                                                                // Указание на отсутствие выявленных нарушений обязательных требований или требований, установленных муниципальными правовыми актами (в случае если нарушений обязательных требований или требований, установленных муниципальными правовыми актами, не выявлено)
	UNIMPOSSIBLE_REASON_I    string                    `xml:"UNIMPOSSIBLE_REASON_I,attr" jsonschema_description:"Сведения о причинах невозможности проведения КНМ (в случае если КНМ не проведено)"`                                                                                                                                                                                                                                             // Сведения о причинах невозможности проведения КНМ (в случае если КНМ не проведено)
	UNDOIG_SEC_I             string                    `xml:"UNDOIG_SEC_I,attr" jsonschema_description:"Сведения об отмене результатов КНМ в случае, если такая отмена была произведена"`                                                                                                                                                                                                                                                        // Сведения об отмене результатов КНМ в случае, если такая отмена была произведена
	I_RESULT_INFORMATION     *I_RESULT_INFORMATION     `xml:"I_RESULT_INFORMATION" json:"I_RESULT_INFORMATION,omitempty" jsonschema_description:"Сведения о результате КНМ"`                                                                                                                                                                                                                                                                     // Сведения о результате КНМ
	I_VIOLATION              []I_VIOLATION             `xml:"I_VIOLATION" json:"I_VIOLATION,omitempty" jsonschema_description:"Нарушение, связанное с результатом КНМ"`                                                                                                                                                                                                                                                                          // Нарушение, связанное с результатом КНМ
	I_RESULT_INSPECTOR       []I_RESULT_INSPECTOR      `xml:"I_RESULT_INSPECTOR" json:"I_RESULT_INSPECTOR,omitempty" jsonschema_description:"Фамилия, имя, отчество (последнее - при наличии) и должность должностного лица (должностных лиц), проводившего КНМ"`                                                                                                                                                                                // Фамилия, имя, отчество (последнее - при наличии) и должность должностного лица (должностных лиц), проводившего КНМ
	I_RESULT_REPRESENTATIVE  []I_RESULT_REPRESENTATIVE `xml:"I_RESULT_REPRESENTATIVE" json:"I_RESULT_REPRESENTATIVE,omitempty" jsonschema_description:"Представители юридического лица, индивидуального предпринимателя, присутствовавшие при проведении КНМ"`                                                                                                                                                                                   // Представители юридического лица, индивидуального предпринимателя, присутствовавшие при проведении КНМ
}

type I_RESULT_INFORMATION struct {
	RESULT_INFORMATION_TYPE_NAME string `xml:"RESULT_INFORMATION_TYPE_NAME,attr" jsonschema_description:"Тип сведений о результате"` // Тип сведений о результате
	TEXT                         string `xml:"TEXT,attr" jsonschema_description:"Формулировка сведения о результате"`                // Формулировка сведения о результате
}

type I_RESULT_REPRESENTATIVE struct {
	FULL_NAME                string `xml:"FULL_NAME,attr" jsonschema_description:"Фамилия, имя, отчество (последнее - при наличии) и должность руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ"` // Фамилия, имя, отчество (последнее - при наличии) и должность руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ
	POSITION                 string `xml:"POSITION,attr" jsonschema_description:"Должность руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ"`                                                     // Должность руководителя, иного должностного лица юридического лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ
	REPRESENTATIVE_TYPE_NAME string `xml:"REPRESENTATIVE_TYPE_NAME,attr" jsonschema_description:"Тип представителя должностного лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ"`                                                                   // Тип представителя должностного лица, уполномоченного представителя юридического лица, уполномоченного представителя индивидуального предпринимателя, присутствовавших при проведении КНМ
}

type I_VIOLATION struct {
	IVIOLATION_TYPE_NAME string               `xml:"IVIOLATION_TYPE_NAME,attr" jsonschema_description:"Характер выявленного нарушения"`                                                                                                                                                                                    // Характер выявленного нарушения
	VIOLATION_NOTE       string               `xml:"VIOLATION_NOTE,attr" jsonschema_description:"Сведения о выявленных нарушениях обязательных требований и требований, установленных муниципальными правовыми актами, об их характере и о лицах, допустивших указанные нарушения (с указанием положений правовых актов)"` // Сведения о выявленных нарушениях обязательных требований и требований, установленных муниципальными правовыми актами, об их характере и о лицах, допустивших указанные нарушения (с указанием положений правовых актов)
	VIOLATION_ACT        string               `xml:"VIOLATION_ACT,attr" jsonschema_description:"Положение нарушенного правового акта"`                                                                                                                                                                                     // Положение нарушенного правового акта
	V_LAWSUIT            *V_LAWSUIT           `xml:"V_LAWSUIT" json:"V_LAWSUIT,omitempty" jsonschema_description:"Судебные сведения о выявленных нарушениях"`                                                                                                                                                              // Судебные сведения о выявленных нарушениях
	V_INJUNCTION         *V_INJUNCTION        `xml:"V_INJUNCTION" json:"V_INJUNCTION,omitempty" jsonschema_description:"Сведения о выданных предписаниях об устранении выявленных нарушений и (или) о проведении мероприятий по предотвращению причинения вреда (реквизиты, срок выполнения, содержание предписания)"`     // Сведения о выданных предписаниях об устранении выявленных нарушений и (или) о проведении мероприятий по предотвращению причинения вреда (реквизиты, срок выполнения, содержание предписания)
	V_CLASSIFICATION_LB  *V_CLASSIFICATION_LB `xml:"V_CLASSIFICATION_LB" json:"V_CLASSIFICATION_LB,omitempty" jsonschema_description:"Положение нарушенного правового акта по выявленным нарушениям обязательных требований и требований, установленных муниципальными правовыми актами."`                                 // Положение нарушенного правового акта по выявленным нарушениям обязательных требований и требований, установленных муниципальными правовыми актами.
}

type V_CLASSIFICATION_LB struct {
	ATR_DATE              *string `xml:"ATR_DATE,attr" json:"ATR_DATE,omitempty" jsonschema_description:"Дата нормативно-правового акта"` // Дата нормативно-правового акта
	ATR_NUMBER            string  `xml:"ATR_NUMBER,attr" jsonschema_description:"Номер нормативно-правового акта"`                        // Номер нормативно-правового акта
	LB_DOCUMENT_NAME      string  `xml:"LB_DOCUMENT_NAME,attr" jsonschema_description:"Положение нормативно-правового акта"`              // Положение нормативно-правового акта
	ATR_I                 string  `xml:"ATR_I,attr" jsonschema_description:"Положение нормативно-правового акта.Раздел"`                  // Положение нормативно-правового акта.Раздел
	ATR_II                string  `xml:"ATR_II,attr" jsonschema_description:"Положение нормативно-правового акта.Глава"`                  // Положение нормативно-правового акта.Глава
	ATR_III               string  `xml:"ATR_III,attr" jsonschema_description:"Положение нормативно-правового акта.Статья"`                // Положение нормативно-правового акта.Статья
	ATR_IV                string  `xml:"ATR_IV,attr" jsonschema_description:"Положение нормативно-правового акта.Пункт"`                  // Положение нормативно-правового акта.Пункт
	ATR_V                 string  `xml:"ATR_V,attr" jsonschema_description:"Положение нормативно-правового акта.Часть"`                   // Положение нормативно-правового акта.Часть
	LB_TYPE_POINTING_NAME string  `xml:"LB_TYPE_POINTING_NAME,attr" jsonschema_description:"Тип положения нормативно-правового акта"`     // Тип положения нормативно-правового акта
}

type V_INJUNCTION struct {
	CODE               string  `xml:"CODE,attr" jsonschema_description:"Реквизиты предписания об устранении выявленных нарушений в результате проведения КНМ"`                                                                    // Реквизиты предписания об устранении выявленных нарушений в результате проведения КНМ
	DATE_APPOINTMENT   *string `xml:"DATE_APPOINTMENT,attr" json:"DATE_APPOINTMENT,omitempty" jsonschema_description:"Дата вынесения предписания об устранении выявленных нарушений в результате проведения КНМ"`                 // Дата вынесения предписания об устранении выявленных нарушений в результате проведения КНМ
	EXECUTION_DEADLINE *string `xml:"EXECUTION_DEADLINE,attr" json:"EXECUTION_DEADLINE,omitempty" jsonschema_description:"Срок выполнения предписания об устранении выявленных нарушений в результате проведения КНМ"`            // Срок выполнения предписания об устранении выявленных нарушений в результате проведения КНМ
	NOTE               string  `xml:"NOTE,attr" jsonschema_description:"Содержание предписания об устранении выявленных нарушений в результате проведения КНМ"`                                                                   // Содержание предписания об устранении выявленных нарушений в результате проведения КНМ
	EXECUTION_NOTE     string  `xml:"EXECUTION_NOTE,attr" jsonschema_description:"Сведения о выполнении лицом, в отношении которого проводилось КНМ, предписания об устранении выявленных нарушений в результате проведения КНМ"` // Сведения о выполнении лицом, в отношении которого проводилось КНМ, предписания об устранении выявленных нарушений в результате проведения КНМ
	IS_REFUSED         bool    `xml:"IS_REFUSED,attr" jsonschema_description:"Отметка о невыполнении предписания об устранении выявленных нарушений в результате проведения КНМ"`                                                 // Отметка о невыполнении предписания об устранении выявленных нарушений в результате проведения КНМ
}

type V_LAWSUIT struct {
	VLAWSUIT_TYPE_NAME string `xml:"VLAWSUIT_TYPE_NAME,attr" jsonschema_description:"Тип судебных сведений о выявленных нарушениях в результате проведения КНМ"` // Тип судебных сведений о выявленных нарушениях в результате проведения КНМ
	TEXT               string `xml:"TEXT,attr" jsonschema_description:"Формулировка судебного сведения"`                                                         // Формулировка судебного сведения
}

type I_RESULT_INSPECTOR struct {
	FULL_NAME           string `xml:"FULL_NAME,attr" jsonschema_description:"ФИО должностного лица, уполномоченного на проведение КНМ"`           // ФИО должностного лица, уполномоченного на проведение КНМ
	POSITION            string `xml:"POSITION,attr" jsonschema_description:"Должность должностного лица, уполномоченного на проведение КНМ"`      // Должность должностного лица, уполномоченного на проведение КНМ
	INSPECTOR_TYPE_NAME string `xml:"INSPECTOR_TYPE_NAME,attr" jsonschema_description:"Тип должностного лица, уполномоченного на проведение КНМ"` // Тип должностного лица, уполномоченного на проведение КНМ
}

type I_CHLIST_HEADER struct {
	NAME          string    `xml:"NAME,attr" jsonschema_description:"Наименование проверочного листа"`                                                                                      // Наименование проверочного листа
	APPROVAL      string    `xml:"APPROVAL,attr" jsonschema_description:"Сведения об утверждении проверочного листа"`                                                                       // Сведения об утверждении проверочного листа
	FRGU_ORG_NAME string    `xml:"FRGU_ORG_NAME,attr" jsonschema_description:"Наименование органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)"` // Наименование органа контроля (надзора) из Федерального реестра государственных и муниципальных услуг (ФРГУ)
	I_CHLIST      *I_CHLIST `xml:"I_CHLIST" json:"I_CHLIST,omitempty" jsonschema_description:"Контрольный вопрос"`                                                                          // Контрольный вопрос
}

type I_CHLIST struct {
	POS_ID                  int64  `xml:"POS_ID,attr" jsonschema_description:"Идентификатор вопроса проверочного листа"`              // Идентификатор вопроса проверочного листа
	QUESTION                string `xml:"QUESTION,attr" jsonschema_description:"Вопрос проверочного листа"`                           // Вопрос проверочного листа
	CHLIST_ANSWER_TYPE_NAME string `xml:"CHLIST_ANSWER_TYPE_NAME,attr" jsonschema_description:"Ответ проверочного листа"`             // Ответ проверочного листа
	ANSWER_TEXT             string `xml:"ANSWER_TEXT,attr" jsonschema_description:"Ответ (иное) проверочного листа"`                  // Ответ (иное) проверочного листа
	PROPS                   string `xml:"PROPS,attr" jsonschema_description:"Реквизиты НПА устанавливающего обязательные требования"` // Реквизиты НПА устанавливающего обязательные требования
}

type I_SUPERVISION struct {
	ISUPERVISION_NAME string `xml:"ISUPERVISION_NAME,attr" jsonschema_description:"Вид государственного контроля (надзора)"` // Вид государственного контроля (надзора)
}
